// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(io) {
    return {
      games: [
        {
          firstPlayerId: 0,
          currentPlayerId: 0,
          phaseIndex: 0,
          deck: {
            number: 40
          },
          players: [
            {
              connected: false,
              name: 'Edouard',
              hand: [
                {
                  shortName: "intellect"
                }, {
                  shortName: "carnivorous"
                }, {
                  shortName: "vivaporous"
                }, {
                  shortName: "tailLoss"
                }
              ],
              species: [
                {
                  traits: [],
                  foodEaten: 0
                }, {
                  traits: [
                    {
                      name: "intellect",
                      shortName: "intellect"
                    }, {
                      name: "carnivorous",
                      cost: 1,
                      shortName: "carnivorous"
                    }
                  ],
                  foodEaten: 0
                }
              ]
            }, {
              connected: false,
              name: 'Jacob',
              hand: [
                {
                  shortName: "intellect"
                }, {
                  shortName: "carnivorous"
                }, {
                  shortName: "tailLoss"
                }
              ],
              species: [
                {
                  traits: [],
                  foodEaten: 0
                }, {
                  traits: [
                    {
                      name: "tailLoss",
                      shortName: "tailLoss"
                    }, {
                      name: "vivaporous",
                      cost: 1,
                      shortName: "vivaporous"
                    }
                  ],
                  foodEaten: 0
                }
              ]
            }
          ]
        }
      ],
      getNewPlayerId: function(gameId) {
        var i;
        i = 0;
        while (this.games[gameId].players[i].connected) {
          i++;
        }
        return i;
      },
      filterGame: function(game, id) {
        var copy, i, player, playerCopy, _i, _len, _ref;
        copy = {
          currentPlayerId: game.currentPlayerId,
          phaseIndex: game.phaseIndex,
          deck: game.deck,
          firstPlayerId: game.firstPlayerId,
          players: []
        };
        _ref = game.players;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          player = _ref[i];
          if (id === i) {
            copy.players.push(player);
          } else {
            playerCopy = {};
            playerCopy.connected = player.connected;
            playerCopy.name = player.name;
            playerCopy.species = player.species;
            playerCopy.cardNumber = player.hand.length;
            copy.players.push(playerCopy);
          }
        }
        return copy;
      }
    };
  };

}).call(this);

//# sourceMappingURL=evolutionController.map
