// Generated by CoffeeScript 1.7.1
(function() {
  var EvolutionCommons, app, clone, evolution, gameId, gameInit, http, io, socketData;

  app = require("express")();

  http = require("http").Server(app);

  EvolutionCommons = require("./EvolutionCommons.js");

  io = require('socket.io')(http);

  evolution = require('./evolutionController.js')(io);

  gameId = 0;

  clone = function(a) {
    return JSON.parse(JSON.stringify(a));
  };

  gameInit = clone(evolution.games[0]);

  evolution.games[0].ec = new EvolutionCommons(evolution.games[0]);

  socketData = {};

  app.get("/", function(req, res) {
    res.send({
      connected: true
    });
  });

  io.on("connection", function(socket) {
    var ec, fakeTurn, game, goToExtinctionAndEvolutionPhase, goToFoodPhase, sData, validState;
    console.log("a user connected");
    sData = function() {
      return socketData[socket.id];
    };
    game = function() {
      return sData().game;
    };
    ec = function() {
      return game().ec;
    };
    validState = function(phase, playerId) {
      if (!ec().phase() === phase && ec().currentPlayerId === sData().playerId) {
        emit("evolution error", {
          message: "haloumi!"
        });
        return false;
      }
      return true;
    };
    fakeTurn = function(game) {
      var action;
      if (game.currentPlayerId !== socketsData().playerId) {
        game = game();
        action = {};
        action.previousPlayerId = game.currentPlayerId;
        evolution.nextPlayer(game);
        action.currentPlayerId = game.currentPlayerId;
        setTimeout(function() {
          socket.emit("player passed", action);
          fakeTurn(game);
        }, 5000);
      }
    };
    goToFoodPhase = function(socket, game) {
      var action;
      action = {};
      switch (game.players.length) {
        case 2:
          action.foodAmount = Math.ceil(Math.random() * 6) + 2;
          break;
        case 3:
          action.foodAmount = Math.ceil(Math.random() * 6) * Math.ceil(Math.random() * 6);
          break;
        case 4:
          action.foodAmount = Math.ceil(Math.random() * 6) * Math.ceil(Math.random() * 6) + 2;
      }
      game.foodAmount = action.foodAmount;
      socket.to(sData().room).emit("phase food", action);
      socket.emit("phase food", action);
    };
    goToExtinctionAndEvolutionPhase = function(socket, game) {
      var action, currentPlayer, nCardsDealed, nCardsRequired, player, playersCardNumber, random, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _ref2;
      random = function(array) {
        return array[Math.floor(Math.random() * array.length)];
      };
      ec().clearExtinctedSpecies();
      nCardsRequired = 0;
      _ref = game.players;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        player = _ref[_i];
        player.nCardsRequired = player.species.length + 1;
        nCardsRequired += player.nCardsRequired;
      }
      nCardsDealed = 0;
      currentPlayer = game.firstPlayerId;
      while (nCardsDealed < nCardsRequired && game.deck.number > 0) {
        player = game.players[currentPlayer];
        if (player.nCardsRequired > 0) {
          player.hand.push(random(ec().cards));
          player.nCardsRequired--;
          nCardsDealed++;
          game.deck.number--;
        }
        currentPlayer = (currentPlayer + 1) % game.players.length;
      }
      playersCardNumber = [];
      _ref1 = game.players;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        player = _ref1[_j];
        playersCardNumber.push(player.hand.length);
      }
      _ref2 = game.players;
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        player = _ref2[_k];
        action = {
          hand: player.hand,
          playersCardNumber: playersCardNumber,
          deckCards: game.deck.number
        };
        socket.server.to(player.socketId).emit("phase evolution", action);
      }
    };
    socket.on('disconnect', function() {
      var _ref, _ref1;
      console.log("disconnect");
      if ((((_ref = sData()) != null ? _ref.gameId : void 0) != null) && (((_ref1 = sData()) != null ? _ref1.playerId : void 0) != null)) {
        console.log("disconnected: player: " + sData().playerId + ", game: " + sData().gameId);
        evolution.games[sData().gameId].players[sData().playerId].connected = false;
      }
      if (sData() != null) {
        delete sData();
      }
    });
    socket.on("pass phase evolution", function() {
      var nextPhase;
      if (!validState("Evolution")) {
        return;
      }
      nextPhase = ec().playerPassedEvolution();
      socket.to(sData().room).emit("player passed evolution");
      socket.emit("player passed evolution");
      if (nextPhase) {
        goToFoodPhase(socket, game());
      }
    });
    socket.on("end turn evolution", function(action) {
      var card, nextPhase, specie, valid;
      if (!validState("Evolution")) {
        return;
      }
      console.log("end turn evolution: ");
      console.log(action);
      valid = true;
      if (action.addSpecie) {
        nextPhase = ec().addSpecie(action.cardIndex);
      } else {
        specie = ec().specie(action.specieIndex);
        card = ec().card(action.cardIndex);
        action.card = card;
        ec().checkCompatibleEvolution(specie, card);
        if (specie.compatible) {
          nextPhase = ec().addTrait(action.specieIndex, action.cardIndex);
        } else {
          action.message = "Error: cards are not compatible.";
          socket.emit("evolution error", action);
          valid = false;
        }
      }
      if (valid) {
        socket.to(sData().room).emit("next player evolution", action);
        if (nextPhase) {
          goToFoodPhase(socket, game());
        }
      }
    });
    socket.on("end turn food", function(action) {
      var nextPhase;
      if (!validState("Food")) {
        return;
      }
      console.log("end turn food: ");
      console.log(action);
      if (!ec().isFed(ec().specie(action.specieIndex))) {
        nextPhase = ec().feedSpecie(action.specieIndex);
        socket.to(sData().room).emit("next player food", action);
        if (nextPhase) {
          goToExtinctionAndEvolutionPhase(socket, game());
        }
      } else {
        action.message = "Error: Specie is fed.";
        socket.emit("evolution error", action);
      }
    });
    socket.on("pass phase food", function() {
      var nextPhase;
      if (!validState("Evolution")) {
        return;
      }
      nextPhase = ec().playerPassedFood();
      socket.to(sData().room).emit("player passed food");
      socket.emit("player passed food");
      if (nextPhase) {
        goToExtinctionAndEvolutionPhase(socket, game());
      }
    });
    socket.on("load game", function(data) {
      var filteredGame, playerId, _ref, _ref1;
      socketData[socket.id] = {};
      if ((data.gameId != null) && (data.playerId != null) && !((_ref = evolution.games[data.gameId]) != null ? (_ref1 = _ref.players[data.playerId]) != null ? _ref1.connected : void 0 : void 0)) {
        console.log("player existed");
        evolution.games[data.gameId].players[data.playerId].connected = true;
        sData().playerId = data.playerId;
        sData().gameId = data.gameId;
        sData().room = "game" + data.gameId;
      } else if (!((data.gameId != null) && (data.playerId != null))) {
        console.log("player did not exist");
        playerId = evolution.getNewPlayerId(gameId);
        sData().playerId = playerId;
        sData().gameId = gameId;
        evolution.games[gameId].players[playerId].connected = true;
        sData().room = "game" + gameId;
      } else {
        console.log("Error: player existed and was connected");
        socket.emit("game error", "A player is already connected on game " + data.gameId + " with the id " + data.playerId + ".");
        return;
      }
      socket.join(sData().room);
      console.log("load game " + data.gameId + " for player: " + data.playerId);
      sData().game = evolution.games[sData().gameId];
      ec().player(sData().playerId).socketId = socket.id;
      filteredGame = evolution.filterGame(game(), sData().playerId);
      socket.emit("game loaded", {
        playerId: sData().playerId,
        gameId: sData().gameId,
        game: filteredGame
      });
    });
    socket.on("restart game", function() {
      console.log("restart game");
      evolution.games[0] = clone(gameInit);
      evolution.games[0].ec = new EvolutionCommons(evolution.games[0]);
      socket.to(sData().room).emit("evolution connect");
      socket.emit("evolution connect");
    });
    socket.on("error", function(error) {
      console.log(error);
      throw error;
    });
  });

  http.listen(3000, function() {
    console.log("listening on *:3000");
  });

}).call(this);

//# sourceMappingURL=index.map
